services:
  db:
    image: postgis/postgis:15-3.4
    container_name: carpool_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: carpool
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:7.0-alpine
    container_name: carpool_redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    restart: always
volumes:
  pgdata: